---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by giaco.
--- DateTime: 30/07/2024 18:48
---

concommand.Add("spawn_chasing_nextbot", function(ply, cmd, args)
    if not IsValid(ply) then return end

    local nextbot = ents.Create("chasing_nextbot")
    nextbot:SetPos(ply:GetPos() + ply:GetForward() * 100)
    nextbot:Spawn()
end)