---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 29/07/2024 11:06
---

DEFINE_BASECLASS("player");

-- Define the NextBot entity
ENT.Base = "base_nextbot"
ENT.Type = "nextbot"
ENT.PrintName = "My NextBot"
ENT.Category = "MyNextBot"


function ENT:Initialize()
    self:SetModel(self.Model)
    self:SetCollisionBounds(Vector(-16, -16, 0), Vector(16, 16, 64))

    self:EmitSound(self.SoundPath)
end